spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default_schema: public
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  resources:
    add-mappings: true
    static-locations: classpath:/static/
  mail:
    host: smtp.gmail.com
    port: 587
    username: romatempforjet@gmail.com
    password: ydkl aobk ctcc jloj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
