spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default_schema: public
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  resources:
    add-mappings: true
    static-locations: classpath:/static/