create table if not exists groups(
    id bigint primary key generated by default as identity,
    name varchar(50) not null,
    average_performance decimal default 0.0
);

create table if not exists subjects(
    id bigint generated by default as identity primary key ,
    title varchar(100) not null
);

create table if not exists labas(
    id bigint primary key generated by default as identity ,
    number int not null,
    title varchar(100),
    subject_id int references subjects(id) on delete cascade not null
);

create table if not exists students(
    id bigint primary key generated by default as identity,
    fio varchar(50) not null,
    group_id int references groups(id) on delete cascade not null,
    date_of_birth date,
    performance decimal default 0.0
);

create table if not exists zachety(
    id bigint primary key generated by default as identity,
    student_id bigint references students(id) on delete cascade not null,
    value varchar(2) not null default '-',
    laba_id bigint references labas(id) on delete cascade not null
);

create table if not exists users(
    id bigint primary key generated by default as identity ,
    username varchar(50) not null,
    password varchar not null ,
    email varchar not null ,
    role varchar(20),
    date_of_registration date
);

create table if not exists group_subject(
    subject_id bigint references subjects(id) on delete cascade not null,
    group_id bigint references groups(id) on delete cascade not null ,
    constraint group_subject_pk primary key (subject_id, group_id)
);